version: '3.8'

services:
  postgres:
    container_name: postgres
    env_file: .env
    image: postgres:13
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - db_data:/postgres/data

  redis:
    container_name: redis
    env_file: .env
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - db_data:/redis/data

volumes:
  db_data:
