name: unit-test
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
jobs:
  build:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          # this will use the latest Node 12 version
          node-version: 14.x
      # Install deps
      - name: Install
        run: yarn
        # Run tests
      - name: Test
        run: yarn test:unit
